/// Locale enum generated by "i18n_codegen"
#[derive(Copy, Clone, Debug)]
pub enum Locale {
    En,
    Da,
}
#[allow(missing_docs)]
pub struct Name<'a>(pub &'a str);
impl Locale {
    #[allow(missing_docs)]
    pub fn greeting(self, name_: Name<'_>) -> String {
        match self {
            Locale::Da => format!("Hej {name}", name = name_.0),
            Locale::En => format!("Hello {name}", name = name_.0),
        }
    }
    #[allow(missing_docs)]
    pub fn hello_world(self) -> String {
        match self {
            Locale::En => format!("Hello, World!"),
            Locale::Da => format!("Hej, Verden!"),
        }
    }
}
